version: '3'
services:
  web:
    build:
      context: ./nginx
    ports:
      - 8000:80
    volumes:
        - ./nginx/static_content:/usr/share/nginx/html
        - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
  app:
    build: .
    image: ealen/echo-server:0.9.2
    ports:
      - 80:80