## 下記のコマンドで動作確認可能
## curl http://$(minikube ip):$(kubectl get service nginx-service -o=go-template='{{(index .spec.ports 0).nodePort}}')
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.4
          ports:
          - containerPort: 80
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-server
  labels:
    name: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  namespace: echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: ealen/echo-server:0.9.2
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
  namespace: echo-server
spec:
  selector:
    app: echo-server
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 80 # TODO: k8sのネットワークモデルを調査


